SELECT SEQAMOSTRA,
SEQUENCIA,
REPLACE(PERCFORMULA,',','.') AS PERCFORMULA,
CODPROD,AD_NATFISICA,
FORMULA, FORMULADOIS,
VALORMINIMO,
VALORMAXIMO
FROM (
SELECT
QUI.SEQAMOSTRA,
QUI.SEQUENCIA,LPAD(REPLACE(QUI.PERCFORMULA,'%',''),12,0) as PERCFORMULA,
AM.CODPROD,PRO.AD_NATFISICA,
FORM.FORMULA,FORM.FORMULADOIS,
FORM.VALORMINIMO,
FORM.VALORMAXIMO
FROM AD_ANALIQUI QUI
INNER JOIN AD_CTLAMOSTRA AM ON AM.SEQAMOSTRA = QUI.SEQAMOSTRA
INNER JOIN TGFPRO PRO  ON PRO.CODPROD = AM.CODPROD
INNER JOIN AD_FORMULATOL FORM ON  FORM.TIPO = PRO.AD_NATFISICA
WHERE AM.CODPROD = :CODPROD
AND QUI.SEQAMOSTRA = :SEQAMOSTRA
AND QUI.SEQUENCIA = :SEQUENCIA) A
WHERE 1=1
AND PERCFORMULA >= VALORMINIMO
AND PERCFORMULA<=VALORMAXIMO